apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
      - name: mycontainer
        image: joergfa/demo:0.0.1-SNAPSHOT
        args: ["arg1", "arg2"]
        env:
        - name: TEST
          value: "Hello from the environment"
      restartPolicy: Never
  backoffLimit: 4


